routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Auth\AdminLoginController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\GuestController;
use App\Http\Controllers\SchoolController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.home');
})->name('welcome');

Route::get('guest/siswa', function () {
    return view('student');
})->name('student');

Route::post('guest/siswa/pencarian', [GuestController::class,'search'])->name('search');

Route::get('/tes', function () {
    //Artisan::call('migrate:fresh --seed');
    return view("letter.letter_format");
});

// Route::get('/maintenance', function () {
//     Artisan::call('down --secret="ag2Vk5hfUfVfJfhBvvWz"');
//     return "maintenance on";
// });

// Route::get('/up', function () {
//     Artisan::call('up');
//     return "maintenance off";
// });

Auth::routes();

Route::get('/admin/login', [AdminLoginController::class,'showLoginForm'])->name('admin.login');
Route::post('/admin/login', [AdminLoginController::class,'login'])->name('admin.login.post');
Route::post('/admin/logout', [AdminLoginController::class,'logout'])->name('admin.logout');
Route::get('/admin/reload-captcha', [AdminLoginController::class, 'reloadCaptcha']);
Route::get('/reload-captcha', [LoginController::class, 'reloadCaptcha']);
//Admin Home page after login
Route::group(['middleware'=>'auth:web,admin'], function() {
    Route::get('/admin/home', [HomeController::class,'index'])->name('admin.home');
    Route::post('/admin/cari-siswa', [HomeController::class,'searchStudent'])->name('dashboard.search');
    Route::resource('siswa', StudentController::class);
    Route::post('/siswa/cari', [StudentController::class,'searchStudent'])->name('search.student');
    Route::resource('akun-sekolah', UserController::class);
    Route::resource('sekolah', SchoolController::class);
    Route::post('siswa-import', [StudentController::class,'studentImport'])->name('student.import');
    Route::post('siswa-update-import', [StudentController::class,'studentUpdateImport'])->name('student.import.update');
    Route::get('format-export-siswa', [StudentController::class,'studentExportFormat'])->name('student.format.export');
    Route::get('/siswa-sd', [StudentController::class,'indexSd'])->name('student.sd');
    Route::get('/siswa-smp', [StudentController::class,'indexSmp'])->name('student.smp');
    Route::get('/admin/download-file/{type}/name/{name}', [HomeController::class,'downloadFile'])->name('admin.download');
    Route::get('surat-keterangan/{id}', [StudentController::class,'statementLetter'])->name('statement_letter');
    Route::get('format-surat-keterangan/{id}', [HomeController::class,'downloadLetter'])->name('statement_letter2');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Student.php
<?php

namespace App\Models;

use App\Models\Utilities\FilterBuilder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;

    protected $casts = [
        'birth_date' => 'date:Y-m-d'
    ];

    protected $fillable = [
        'nisn',
        'name',
        // 'address',
        'birth_place',
        'birth_date',
        'religion',
        'gender',
        'father_name',
        // 'father_phone',
        // 'mother_name',
        // 'mother_phone',
        'guardian_name',
        // 'guardian_phone',
        'school_id',
        // 'entry_year',
        'graduated_year',
        'school_year',
        'ijazah',
        'ijazah_number',
        'photo'
    ];

    public function setBirthDateAttribute($value)
    {
        $this->attributes['birth_date'] = date('Y-m-d', strtotime($value));
    }

    public function scopeDashboardSearch($querry,$request)
    {
        return $querry->where('school_id',$request['school_id'])
        ->where('nisn','like','%'.$request['nisn'].'%');
    }

    public function scopeSearch($querry,$value,$school = Null)
    {
        if ($school) {
            return $querry->where('nisn','like','%'.$value.'%')
            ->orWhere('name','like','%'.$value.'%')
            ->where('school_id',$school);
        }else {
            return $querry->where('nisn','like','%'.$value.'%')
            ->orWhere('name','like','%'.$value.'%');
        }

    }

    public function scopeFilterBy($query, $filters)
    {
        $namespace = 'App\Utilities\StudentFilters';
        $filter = new FilterBuilder($query, $filters, $namespace);
        return $filter->apply();
    }

    public function scopeGuestSearch($querry,$request)
    {
        return $querry->Where('nisn','like','%'.$request['nisn'].'%');
    }

    public function school()
    {
       return $this->belongsTo(School::class,'school_id');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Exports\StudentImportFormat;
use App\Http\Requests\StoreStudentRequest;
use App\Http\Requests\UpdateStudentRequest;
use App\Imports\StudentsImport;
use App\Imports\StudentsUpdateImport;
use App\Models\School;
use App\Models\Student;
use Barryvdh\DomPDF\Facade as PDF;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page = "Siswa";
        $students = Student::with('school')->where('school_id',auth()->guard('web')->user()->school_id)->paginate();

        return view('admin.student.index',compact('students','page'));
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function indexSd()
    {
        $page = "Siswa SD";
        $students = Student::with('school')->whereHas('school',function($q){$q->where("level","sd");})->paginate();

        return view('admin.student.index',compact('students','page'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function indexSmp()
    {
        $page = "Siswa SMP";
        $students = Student::with('school')->whereHas('school',function($q){$q->where("level","smp");})->paginate();

        return view('admin.student.index',compact('students','page'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page = "Siswa";
        $genders = array('L','P');
        $levels = array('sd','smp');
        $religions = array('Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu');
        if (auth()->guard("admin")->check()) {
            $schools = School::all();
        }else{
            $schools = School::find(auth()->guard("web")->user()->school_id);
        }

        return view('admin.student.create',compact('page','genders','religions','levels','schools'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreStudentRequest $request)
    {
        DB::beginTransaction();
        try {
            $student = Student::create($request->all());
            if ($ijazah = $request->file('ijazah')) {
                $name = $request->name.'-'.time().'.'.$ijazah->getClientOriginalExtension();
                $student->ijazah = $name;
                $ijazah = $request->ijazah->storeAs('ijazah',$name);
                $student->save();
            }
            if ($photo = $request->file('photo')) {
                $name = $request->name.'-'.time().'.'.$photo->getClientOriginalExtension();
                $student->photo = $name;
                $photo = $request->photo->storeAs('public/photos',$name);
                $student->save();
            }
            DB::commit();
            // all good
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('siswa.create')->withErrors(['message'=>$e->getMessage()]);
        }

        if (auth()->guard('admin')->check()) {
            if (School::where("id",$request->school_id)->where("level","sd")) {
                return redirect()->route('student.sd')->with('success','Berhasil menambah data');
            }elseif(School::where("id",$request->school_id)->where("level","smp")){
                return redirect()->route('student.smp')->with('success','Berhasil menambah data');
            }
        }

        return redirect()->route('siswa.index')->with('success','Berhasil menambah data');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $page = "Detail Siswa";
        $student = Student::find($id);
        return view('admin.student.show',compact('student','page'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page = "Siswa";
        $genders = array('L','P');
        $levels = array('sd','smp');
        $religions = array('Islam', 'Kristen', 'Katolik', 'Hindu', 'Buddha', 'Konghucu');
        if (auth()->guard("admin")->check()) {
            $schools = School::all();
        }else{
            $schools = School::find(auth()->guard("web")->user()->school_id);
        }
        $student = Student::find($id);
        return view('admin.student.edit',compact('student','page','genders','levels','religions','schools'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateStudentRequest $request, $id)
    {
        $page = "Siswa";
        DB::beginTransaction();
        try {
            $student = Student::findOrFail($id);
            if ($ijazah = $request->file('ijazah')) {
                Storage::delete('ijazah/'.$student->ijazah);
                $name = $request->name.'-'.time().'.'.$ijazah->getClientOriginalExtension();
                $student->ijazah = $name;
                $request->ijazah->storeAs('ijazah',$name);
            }
            if ($photo = $request->file('photo')) {
                Storage::delete('photo/'.$student->photo);
                $name = $request->name.'-'.time().'.'.$photo->getClientOriginalExtension();
                $student->photo = $name;
                $request->photo->storeAs('public/photos',$name);
            }
            $student->nisn = $request->nisn;
            $student->name = $request->name;
            // $student->address = $request->address;
            $student->birth_place = $request->birth_place;
            $student->birth_date = $request->birth_date;
            $student->religion = $request->religion;
            $student->gender = $request->gender;
            $student->father_name = $request->father_name;
            // $student->father_phone = $request->father_phone;
            // $student->mother_name = $request->mother_name;
            // $student->mother_phone = $request->mother_phone;
            $student->guardian_name = $request->guardian_name;
            // $student->guardian_phone = $request->guardian_phone;
            // $student->entry_year = $request->entry_year;
            $student->graduated_year = $request->graduated_year;
            $student->ijazah_number = $request->ijazah_number;

            $student->update();
            DB::commit();
            // all good
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('siswa.edit',$id)->withErrors(['message'=>$e->getMessage()]);
        }

        if (auth()->guard('admin')->check()) {
            if (School::where("id",$request->school_id)->where("level","sd")) {
                return redirect()->route('student.sd')->with('success','Berhasil merubah data');
            }elseif(School::where("id",$request->school_id)->where("level","smp")){
                return redirect()->route('student.smp')->with('success','Berhasil merubah data');
            }
        }

        return redirect()->route('siswa.index')->with('success','Berhasil merubah data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Student  $student
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $student = Student::find($id);
        $schoolId = $student->school_id;
        Storage::delete('ijazah/'.$student->ijazah);
        Storage::delete('photos/'.$student->photo);
        $student->delete();
        if (auth()->guard('admin')->check()) {
            if (School::where("id",$schoolId)->where("level","sd")) {
                return redirect()->route('student.sd')->with('success','Berhasil menghapus data');
            }elseif(School::where("id",$schoolId)->where("level","smp")){
                return redirect()->route('student.smp')->with('success','Berhasil menghapus data');
            }
        }
        return redirect()->route('siswa.index')->with('success','Berhasil menghapus data');
    }

    public function statementLetter($id)
    {
        $student = Student::with('school')->find($id);
        // return view('letter.statement_letter',compact('student'));
        $pdf = PDF::loadView('letter.statement_letter', compact('student'));
        return $pdf->download('invoice.pdf');
    }

    public function studentImport(Request $request)
    {

        if (auth()->guard('admin')->check()) {
            Excel::import(new StudentsImport(), $request->file('studentImport'));
        } else {
            Excel::import(new StudentsImport(auth()->guard('web')->user()->school_id), $request->file('studentImport'));
        }

        if ($request->page=="Siswa SD") {
            return redirect()->route('student.sd')->with('success','Berhasil import data');
        }elseif($request->page=="Siswa SMP"){
            return redirect()->route('student.smp')->with('success','Berhasil import data');
        }else{
            return redirect()->route('siswa.index')->with('success','Berhasil import data');
        }
    }

    public function studentUpdateImport(Request $request)
    {
        if (auth()->guard('admin')->check()) {
            Excel::import(new StudentsUpdateImport(), $request->file('studentUpdateImport'));
        } else {

resources/views/admin/student/index.blade.php
@extends('base')
@section('plugin')
    <!-- bs-custom-file-input -->
    <script src="{{asset('assets/plugins/bs-custom-file-input/bs-custom-file-input.min.js')}}"></script>
@endsection
@section('content')
<!-- Content Header (Page header) -->
<x-page-header :name="$page"/>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <div id="accordion">
            <div class="card card-primary">
                <div class="card-header">
                  <h4 class="card-title w-100">
                    <a class="d-block w-100" data-toggle="collapse" href="#collapseOne">
                        <span><i class="nav-icon fas fa-search"></i></span>&nbsp;&nbsp;Pencarian
                    </a>
                  </h4>
                </div>
                <div id="collapseOne" class="collapse @isset($request) show @endisset" data-parent="#accordion">
                    <form action="{{route('search.student')}}" method="POST">
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="value">NISN/Nama Siswa</label>
                                <input type="text" class="form-control" id="value" name="name" placeholder="masukan NISN/Nama Siswa" value="{{old('nisn',$request->value ?? "")}}" required>
                            </div>
                        </div>
                        @if ($page=="Siswa SD")
                            <input type="hidden" name="level" value="sd">
                        @elseif ($page=="Siswa SMP")
                            <input type="hidden" name="level" value="smp">
                        @endif
                        <!-- /.card-body -->
                        <div class="card-footer">
                          <button type="submit" class="btn btn-primary">Cari</button>
                            @isset($request)
                            @if ($page=="Siswa SD")
                                <a href="{{route('student.sd')}}" class="btn btn-danger">Batalkan</a>
                            @elseif ($page=="Siswa SMP")
                                <a href="{{route('student.smp')}}" class="btn btn-danger">Batalkan</a>
                            @else
                                <a href="{{route('siswa.index')}}" class="btn btn-danger">Batalkan</a>
                            @endif
                          @endisset
                        </div>
                      </form>
                </div>
            </div>
        </div>


        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card">
                    <div class="card-header">
                        <div style="float:left" class="card-title">List Data</div>
                        <div style="float:right">
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <button type="button" class="btn btn-default btn-sm" data-toggle="modal"
                                    data-target="#modal-sm">
                                    Import Data Siswa
                                </button>
                                <button type="button" class="btn btn-warning btn-sm" data-toggle="modal"
                                    data-target="#modal-2">
                                    Import Perbarui Data Siswa
                                </button>
                                <a href="{{route('siswa.create')}}" class="btn btn-primary btn-sm">Tambah Data</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th style="width: 10px">#</th>
                                    <th>Nama</th>
                                    <th>NISN</th>
                                    <th>Tahun Pelajaran</th>
                                    <th>Nama Orang Tua</th>
                                    <th>Asal Sekolah</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $x=1?>
                                @foreach ($students as $key => $student)
                                <tr>
                                    <td>{{$students->firstItem() + $key}}</td>
                                    <td>{{$student->name}}</td>
                                    <td>{{$student->nisn}}</td>
                                    <td>{{$student->school_year}}</td>
                                    <td>{{$student->father_name}}</td>
                                    <td>{{$student->school->name ?? ""}}</td>
                                    <td>
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <a class="btn btn-info" href="{{route('siswa.show',$student->id)}}"><i
                                                    class="fa fa-eye"></i></a>
                                            <a class="btn btn-warning" href="{{route('siswa.edit',$student->id)}}"><i
                                                    class="fa fa-pen"></i></a>
                                            <form action="{{route('siswa.destroy',$student->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-danger delete-data" type="submit"><i
                                                        class="fa fa-trash"></i></button>
                                            </form>
                                            <a class="btn btn-info" href="{{route('statement_letter',$student->id)}}"
                                                target="_blank"><i class="fa fa-file"></i></a>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    {{$students->setPath(url()->current())->links('pagination::bootstrap-4')}}
                </div>
                <!-- /.card -->
            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->
        <div class="modal fade" id="modal-sm">
            <div class="modal-dialog modal-md">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Import Data Siswa</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="{{route('student.import')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="modal-body">
                            <p>Pastikan mengikuti format excel yang telah disediakan sebelum melakukan import data</p>
                            <p><a href="{{route('student.format.export')}}" class="btn btn-success btn-sm">Download
                                    Format Excel</a></p>

                            <div class="form-group">
                                <label for="studentImport">Upload File Excel</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="studentImport"
                                            name="studentImport" required>
                                        <label class="custom-file-label" for="studentImport">Pilih file</label>
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" name="page" value="{{$page}}">

                        </div>
                        <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Proses</button>
                        </div>
                </div>
                </form>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>

        <div class="modal fade" id="modal-2">
            <div class="modal-dialog modal-md">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Import Perbarui Data Siswa</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="{{route('student.import.update')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="modal-body">
                            <p>Pastikan mengikuti format excel yang telah disediakan sebelum melakukan import data, fitur ini hanya untuk melakukan pengupdatean berdasarkan nisn yang sudah terdaftar di sistem, jadi jika ada nisn baru tidak akan terinput maka untuk import data siswa baru silahkan gunakan fitur <b>Import Data Siswa</b></p>
                            <p><a href="{{route('student.format.export')}}" class="btn btn-success btn-sm">Download
                                    Format Excel</a></p>

                            <div class="form-group">
                                <label for="studentImport">Upload File Excel</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="studentImport"
                                            name="studentUpdateImport" required>
                                        <label class="custom-file-label" for="studenUpdatetImport">Pilih file</label>
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" name="page" value="{{$page}}">

                        </div>
                        <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Proses</button>
                        </div>
                </div>
                </form>
                <!-- /.modal-content -->
            </div>
            <!-- /.modal-dialog -->
        </div>
        <!-- /.modal -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

@section('javascript')
<!-- bs-custom-file-input -->
<script src="{{asset('assets/plugins/bs-custom-file-input/bs-custom-file-input.min.js')}}"></script>
<script>
    $(function () {
        //Initialize Select2 Elements
        bsCustomFileInput.init();

    });
  </script>
@endsection