routes/web.php
<?php

use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Auth\AdminLoginController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\GuestController;
use App\Http\Controllers\SchoolController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('admin.home');
})->name('welcome');

Route::get('guest/siswa', function () {
    return view('student');
})->name('student');

Route::post('guest/siswa/pencarian', [GuestController::class,'search'])->name('search');

Route::get('/tes', function () {
    //Artisan::call('migrate:fresh --seed');
    return view("letter.letter_format");
});

// Route::get('/maintenance', function () {
//     Artisan::call('down --secret="ag2Vk5hfUfVfJfhBvvWz"');
//     return "maintenance on";
// });

// Route::get('/up', function () {
//     Artisan::call('up');
//     return "maintenance off";
// });

Auth::routes();

Route::get('/admin/login', [AdminLoginController::class,'showLoginForm'])->name('admin.login');
Route::post('/admin/login', [AdminLoginController::class,'login'])->name('admin.login.post');
Route::post('/admin/logout', [AdminLoginController::class,'logout'])->name('admin.logout');
Route::get('/admin/reload-captcha', [AdminLoginController::class, 'reloadCaptcha']);
Route::get('/reload-captcha', [LoginController::class, 'reloadCaptcha']);
//Admin Home page after login
Route::group(['middleware'=>'auth:web,admin'], function() {
    Route::get('/admin/home', [HomeController::class,'index'])->name('admin.home');
    Route::post('/admin/cari-siswa', [HomeController::class,'searchStudent'])->name('dashboard.search');
    Route::resource('siswa', StudentController::class);
    Route::post('/siswa/cari', [StudentController::class,'searchStudent'])->name('search.student');
    Route::resource('akun-sekolah', UserController::class);
    Route::resource('sekolah', SchoolController::class);
    Route::post('siswa-import', [StudentController::class,'studentImport'])->name('student.import');
    Route::post('siswa-update-import', [StudentController::class,'studentUpdateImport'])->name('student.import.update');
    Route::get('format-export-siswa', [StudentController::class,'studentExportFormat'])->name('student.format.export');
    Route::get('/siswa-sd', [StudentController::class,'indexSd'])->name('student.sd');
    Route::get('/siswa-smp', [StudentController::class,'indexSmp'])->name('student.smp');
    Route::get('/admin/download-file/{type}/name/{name}', [HomeController::class,'downloadFile'])->name('admin.download');
    Route::get('surat-keterangan/{id}', [StudentController::class,'statementLetter'])->name('statement_letter');
    Route::get('format-surat-keterangan/{id}', [HomeController::class,'downloadLetter'])->name('statement_letter2');
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/School.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    use HasFactory;

    protected $fillable = ['name','level','headmaster','nip','letterhead'];

    public function students()
    {
        return $this->hasMany(Student::class);
    }
}

app/Http/Controllers/SchoolController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreSchoolRequest;
use App\Http\Requests\UpdateSchoolRequest;
use App\Models\School;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class SchoolController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $page = "Sekolah";
        $schools = School::paginate(15);

        return view('admin.school.index',compact('schools','page'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page = "Sekolah";
        $levels = array('sd','smp');

        return view('admin.school.create',compact('page','levels'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreSchoolRequest $request)
    {
        DB::beginTransaction();
        try {
            $school = School::create($request->all());
            // if ($letterhead = $request->file('letterhead')) {
            //     $name = $request->name.'-'.time().'.'.$letterhead->getClientOriginalExtension();
            //     $school->letterhead = $name;
            //     $letterhead = $request->letterhead->storeAs('public/letterheads',$name);
            //     $school->save();
            // }
            DB::commit();
            // all good
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('sekolah.create')->withErrors(['message'=>$e->getMessage()]);
        }

        return redirect()->route('sekolah.index')->with('success','Berhasil menambah data');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\School  $school
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $page = "Detail Siswa";
        $school = School::find($id);
        return view('admin.School.show',compact('School','page'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\School  $school
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page = "Sekolah";
        $school = School::find($id);
        $levels = array('sd','smp');
        return view('admin.school.edit',compact('school','page','levels'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\School  $school
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateSchoolRequest $request, $id)
    {
        $page = "Sekolah";
        DB::beginTransaction();
        try {
            $school = School::findOrFail($id);
            if ($letterhead = $request->file('letterhead')) {
                Storage::delete('letterhead/'.$school->letterhead);
                $name = $request->name.'-'.time().'.'.$letterhead->getClientOriginalExtension();
                $school->letterhead = $name;
                $request->letterhead->storeAs('public/letterheads',$name);
            }
            $school->nip = $request->nip;
            $school->name = $request->name;
            $school->headmaster = $request->headmaster;
            $school->level = $request->level;

            $school->update();
            DB::commit();
            // all good
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('sekolah.edit',$id)->withErrors(['message'=>$e->getMessage]);
        }

        return redirect()->route('sekolah.index')->with('success','Berhasil merubah data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\School  $school
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $school = School::find($id);
        // $schoolId = $school->school_id;
        // Storage::delete('letterhead/'.$school->letterhead);
        $school->delete();

        return redirect()->route('sekolah.index')->with('success','Berhasil menghapus data');
    }

}

resources/views/admin/school/create.blade.php
@extends('base')
@section('plugin')
    <!-- Select2 -->
    <link rel="stylesheet" href="{{asset('assets/plugins/select2/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
    <!-- bs-custom-file-input -->
    <script src="{{asset('assets/plugins/bs-custom-file-input/bs-custom-file-input.min.js')}}"></script>
@endsection
@section('content')
<!-- Content Header (Page header) -->
<x-page-header :name="$page"/>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        <li>Proses Gagal!!!</li>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Tambah Data Siswa</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form action="{{route('sekolah.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">Nama Sekolah</label>
                                <input type="text" class="form-control" id="name" name="name"
                                    placeholder="Masukan Nama Sekolah" required>
                            </div>
                            <div class="form-group">
                                <label for="headmaster">Nama Kepala Sekolah</label>
                                <input type="text" class="form-control" id="headmaster" name="headmaster"
                                    placeholder="Masukan Nama Kepala Sekolah" required>
                            </div>
                            <div class="form-group">
                                <label for="nip">NIP Kepala Sekolah</label>
                                <input type="text" class="form-control" id="nip" name="nip"
                                    placeholder="Masukan NIP Kepala Sekolah" required>
                            </div>
                            <div class="form-group">
                                <label>Tingkat Sekolah</label>
                                <select class="form-control select2" style="width: 100%;" name="level">
                                    @foreach ($levels as $level)
                                    <option value="{{$level}}">{{$level}}</option>
                                    @endforeach
                                </select>
                            </div>



                            {{-- <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="form-col-form-label" for="letterhead">kop surat</label>
                                        <input class="form-control-file" type="file" accept="image/*" name="letterhead" onchange="preview_image(event)">
                                        <br>
                                        <img style="width:100%" id="output_image"/>
                                    </div>
                                </div>
                            </div> --}}
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                            <a href="{{route('sekolah.index')}}" class="btn btn-danger">Batal</a>
                        </div>
                    </form>
                </div>
                <!-- /.card -->

            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection
@section('javascript')
<!-- Select2 -->
<script src="{{asset('assets/plugins/select2/js/select2.full.min.js')}}"></script>
<!-- bs-custom-file-input -->
<script src="{{asset('assets/plugins/bs-custom-file-input/bs-custom-file-input.min.js')}}"></script>
<script>
    $(function () {
        //Initialize Select2 Elements
        bsCustomFileInput.init();
        $('.select2').select2()
        //Date picker
    });
    function preview_image(event) {
        var reader = new FileReader();
        reader.onload = function () {
            var output = document.getElementById('output_image');
            output.src = reader.result;
        }
        reader.readAsDataURL(event.target.files[0]);
    }
  </script>
@endsection

resources/views/admin/school/edit.blade.php
@extends('base')
@section('plugin')
    <!-- Select2 -->
    <link rel="stylesheet" href="{{asset('assets/plugins/select2/css/select2.min.css')}}">
    <link rel="stylesheet" href="{{asset('assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
    <!-- bs-custom-file-input -->
    <script src="{{asset('assets/plugins/bs-custom-file-input/bs-custom-file-input.min.js')}}"></script>
@endsection
@section('content')
<!-- Content Header (Page header) -->
<x-page-header :name="$page"/>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        <li>Proses Gagal!!!</li>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Edit Data Sekolah</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->
                    <form action="{{route('sekolah.update',$school->id)}}" method="POST" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="name">Nama Sekolah</label>
                                <input type="text" class="form-control" id="name" name="name" value="{{old('name', $school->name)}}"
                                    placeholder="Masukan Nama Sekolah" required>
                            </div>
                            <div class="form-group">
                                <label for="headmaster">Nama Kepala Sekolah</label>
                                <input type="text" class="form-control" id="headmaster" name="headmaster" value="{{old('headmaster', $school->headmaster)}}"
                                    placeholder="Masukan Nama Kepala Sekolah" required>
                            </div>
                            <div class="form-group">
                                <label for="nip">NIP</label>
                                <input type="text" class="form-control" id="nip" name="nip" value="{{old('nip', $school->nip)}}"
                                    placeholder="Masukan NIP" required>
                            </div>
                            <div class="form-group">
                                <label>Tingkat Sekolah</label>
                                <select class="form-control select2" style="width: 100%;" name="level">
                                    @foreach ($levels as $level)
                                    <option value="{{$level}}" @if ($school->level==$level) selected @endif>{{$level}}</option>
                                    @endforeach
                                </select>
                            </div>
                            {{-- <div class="form-group">
                                <label for="ijazah">Foto Siswa</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input class="custom-file-input" type="file" accept="image/*" name="photo" onchange="preview_image(event)">
                                        <label class="custom-file-label" for="photo">Pilih file</label>
                                    </div>
                                </div>
                                <br>
                                <img style="width:30%" id="output_image" src="{{asset('storage/photos/'.$school->photo)}}"/>
                            </div> --}}
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Simpan</button>
                            <a href="{{route('sekolah.index')}}" class="btn btn-danger">Batal</a>
                        </div>
                    </form>
                </div>
                <!-- /.card -->

            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection
@section('javascript')
<!-- Select2 -->
<script src="{{asset('assets/plugins/select2/js/select2.full.min.js')}}"></script>
<!-- bs-custom-file-input -->
<script src="{{asset('assets/plugins/bs-custom-file-input/bs-custom-file-input.min.js')}}"></script>
<script>
    $(function () {
        //Initialize Select2 Elements
        bsCustomFileInput.init();
        $('.select2').select2()
        //Date picker

    });
    function preview_image(event) {
        var reader = new FileReader();
        reader.onload = function () {
            var output = document.getElementById('output_image');
            output.src = reader.result;
        }
        reader.readAsDataURL(event.target.files[0]);
    }
  </script>
@endsection

resources/views/admin/school/index.blade.php
@extends('base')
@section('content')
<!-- Content Header (Page header) -->
<x-page-header :name="$page"/>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card">
                    <div class="card-header">
                        <div style="float:left" class="card-title">List Data</div>
                        <div style="float:right">
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a href="{{route('sekolah.create')}}" class="btn btn-primary btn-sm">Tambah</a>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                      <table class="table table-bordered">
                        <thead>
                          <tr>
                            <th style="width: 10px">#</th>
                            <th>Nama</th>
                            <th>Tingkat</th>
                            <th>Kepala Sekolah</th>
                            <th>NIP</th>
                            <th>Aksi</th>
                          </tr>
                        </thead>
                        <tbody>
                            <?php $x=1?>
                            @foreach ($schools as $key => $school)
                                <tr>
                                    <td>{{$schools->firstItem() + $key}}</td>
                                    <td>{{$school->name}}</td>
                                    <td>{{$school->level}}</td>
                                    <td>{{$school->headmaster}}</td>
                                    <td>{{$school->nip}}</td>
                                    <td>
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <a class="btn btn-warning" href="{{route('sekolah.edit',$school->id)}}"><i
                                                    class="fa fa-pen"></i></a>
                                            <form action="{{route('sekolah.destroy',$school->id)}}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-danger delete-data" type="submit"><i
                                                        class="fa fa-trash"></i></button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                      </table>
                    </div>
                    <!-- /.card-body -->
                    {{$schools->setPath(url()->current())->links('pagination::bootstrap-4')}}
                  </div>
                <!-- /.card -->
            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

resources/views/admin/school/show.blade.php
@extends('base')
@section('content')
<!-- Content Header (Page header) -->
<x-page-header :name="$page"/>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
        @endif
        @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
        @endif
        <div class="row">
                        <div class="col-md-3">

                          <!-- Profile Image -->
                          <div class="card card-primary card-outline">
                            <div class="card-body box-profile">
                              <div class="text-center">
                                <img class="profile-user-img img-fluid img-circle"
                                     src="{{asset('storage/avatars/default.jpg')}}"
                                     alt="User profile picture">
                              </div>

                              <h3 class="profile-username text-center">{{$student->name}}</h3>

                            </div>
                            <!-- /.card-body -->
                          </div>
                          <!-- /.card -->

                        </div>
                        <!-- /.col -->
                        <div class="col-md-9">
                          <div class="card">
                            <div class="card-header p-2">
                              <ul class="nav nav-pills">
                                <li class="nav-item"><a class="nav-link active" href="#settings" data-toggle="tab">Biodata</a></li>
                              </ul>
                            </div><!-- /.card-header -->
                            <div class="card-body">
                              <div class="tab-content">

                                <div class="active tab-pane" id="settings">
                                    <table class="table table-bordered">
                                        <tbody>
                                          <tr>
                                            <td>NIS</td>
                                            <td>{{$student->nis}}</td>
                                          </tr>
                                          <tr>
                                            <td>Nama</td>
                                            <td>{{$student->name}}</td>
                                          </tr>
                                          {{-- <tr>
                                            <td>Alamat</td>
                                            <td>{{$student->address}}</td>
                                          </tr> --}}
                                          <tr>
                                            <td>Tempat Lahir</td>
                                            <td>{{$student->birth_place}}</td>
                                          </tr>
                                          <tr>
                                            <td>Tanggal Lahir</td>
                                            <td>{{date('d-m-Y', strtotime($student->birth_date))}}</td>
                                          </tr>
                                          <tr>
                                            <td>Nama Orang Tua</td>
                                            <td>{{$student->father_name}}</td>
                                          </tr>
                                          <tr>
                                            <td>Agama</td>
                                            <td>{{$student->religion}}</td>
                                          </tr>
                                          <tr>
                                            <td>Jenis Kelamin</td>
                                            <td>{{$student->gender}}</td>
                                          </tr>
                                          {{--
                                          <tr>
                                            <td>Nomor HP Ayah</td>
                                            <td>{{$student->father_phone}}</td>
                                          </tr>
                                          <tr>
                                            <td>Nama Ibu</td>
                                            <td>{{$student->mother_name}}</td>
                                          </tr>
                                          <tr>
                                            <td>Nomor HP Ibu</td>
                                            <td>{{$student->mother_phone}}</td>
                                          </tr>

                                          --}}
                                          <tr>
                                            <td>Nama Wali</td>
                                            <td>{{$student->guardian_name ?? "-"}}</td>
                                          </tr>
                                          {{-- <tr>
                                            <td>Nomor HP Wali</td>
                                            <td>{{$student->guardian_phone ?? "-"}}</td>
                                          </tr> --}}
                                          <tr>
                                            <td>Asal Sekolah</td>
                                            <td>{{$student->school->name}}</td>
                                          </tr>
                                          {{-- <tr>
                                            <td>Angkatan Tahun</td>
                                            <td>{{$student->entry_year}}</td>
                                          </tr>
                                           --}}
                                           <tr>
                                            <td>Lulus Tahun</td>
                                            <td>{{$student->graduated_year}}</td>
                                          </tr>
                                          <tr>
                                            <td>Tahun Pelajaran</td>
                                            <td>{{$student->school_year}}</td>
                                          </tr>
                                          <tr>
                                            <td>Nomor Ijazah</td>
                                            <td>{{$student->ijazah_number ?? "data tidak ada"}}</td>
                                          </tr>
                                          <tr>
                                            <td>Ijazah</td>
                                            @if ($student->ijazah)
                                            <td><a href="{{route('admin.download',['type'=>"certificates",'name'=>$student->ijazah ?? 'default'])}}">Download</a></td>
                                            @else
                                            <td>Data tidak ada</td>
                                            @endif

                                          </tr>
                                        </tbody>
                                      </table>
                                </div>
                                <!-- /.tab-pane -->
                              </div>
                              <!-- /.tab-content -->
                            </div><!-- /.card-body -->
                            <div class="card-footer">
                            <a href="{{route('siswa.index')}}" class="btn btn-danger">Kembali</a>
                        </div>
                          </div>
                          <!-- /.card -->
                        </div>
                        <!-- /.col -->
                      </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection